# Называем 
name: pw test

#Когда запускаем

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Ручной запуск
  workflow_dispatch:
jobs:
  e2eTests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    #Делаем чек-аут
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      #Установка пакетов node
      - name: Устанавливаем пакеты
        run: npm i
        
      #Установка PW
      - name: Установить PW
        run: npx playwright install --with-deps
      - name: Запустить PW
        run: npm run test 
      #Сохраняем отчёт PW
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
  #Сохраняем результаты allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
  #Забираем результаты предыдущего запуска  
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          retention-days: 20
  #Формируем отчёт из allure-results
      - uses: simple:elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure-results: allure-results
          gh-pages: gh-pages
          allure-report: allure-report
          allure-history: allure-history
          keep_reports: 20
  #Деплоим отчёт
      - name: deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history  # default: gh-pages
          
          
